### ISSUE TITLE
File requiered for compilation unavailable 

### ISSUE THREAD

**Issue by slozan0** [IGBB/egads#6]
During compilation the the file ‘msbuffmin.txt’ cannot the read due to local security restrictions (i.e., ftp ports are closed), Would it be possible to have the make file point to another place?  Is rebase in gitHub?

wget -O msbuffmin.txt ftp://ftp.neb.com/pub/rebase/msbuffmin.txt
--2023-10-31 11:28:56--  ftp://ftp.neb.com/pub/rebase/msbuffmin.txt
           => ‘msbuffmin.txt’

**Comment by maa146** [comment]
You can download the file from http://rebase.neb.com/rebase/msbuffmin.txt into the correct location (egads/src/msbuffmin.txt), or modify the url in the makefile ([src/makefile:24](https://github.com/IGBB/egads/blob/main/src/makefile#L24)). 

As far as I can tell rebase is only available on NEB's website. Since the database updates daily, I'm very hesitant to add it to the repo.

**Comment by slozan0** [comment]
Thank you. I'm helping someone else get the app running, so not an expert in the biology. Why would the database be modified daily? I'm asking to see if we should (or how often) update the msbuffmin.txt file 

We modified the makefile and used the ftp file, the app appears to be working as expected.

**Comment by maa146** [comment]
Rebase adds and removes some enzymes as they are found or become obsolete, and update vendor info as it changes. 

Honestly, unless they are doing something fairly novel, I wouldn't update it that often. Maybe once every six months at most.

**Comment by slozan0** [comment]
Got it. Thank you again.
